### PR TITLE
Support  boolean arguments in numpy unique

### PR DESCRIPTION
**Pull request by charlotte12l**
https://github.com/serge-sans-paille/pythran/issues/1842#issuecomment-896320261

Hard code boolean arguments in numpy unique, at first, I only consider the case `len(node.args) >= 4` & `return_index` is true & `return_inverse` is true & `return_counts` is true.  

Next:
- [done]consider the case when `len(node.args) == 3` or `2` 
- [done] support `return_index` is true/false & `return_inverse` is true/false & `return_counts` is true/false.  
- use offset to generalize

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Looks like a good start! Can you rebase on master, then add a few test case?

**Comment by charlotte12l** [comment]
@serge-sans-paille  Sure, done. 

Besides, I'm wondering how Pythran know the default value is false? e.g. for `unique(x, return_inverse=True)`, how does Pythran know it should call `unique(E const &expr, std::false_type return_index, std::true_type return_inverse)` rather than `unique(E const &expr, std::true_type return_index, std::true_type return_inverse)`?

**Comment by serge-sans-paille** [comment]
> Besides, I'm wondering how Pythran know the default value is false?

It's using `inspect.gefullargspecs` to get introspection info and retrieve the default value from the actual code of `numpy.unique` ;-)

**Comment by serge-sans-paille** [comment]
This looks very good to me :-) Can you squash these three commits in one and we're done!

**Comment by charlotte12l** [comment]
> This looks very good to me :-) Can you squash these three commits in one and we're done!

Oh I think I didn't finish adding all the permutations, I made a table, and seems we need support 15 kinds:(?)


No. | return_index | return_inverse | return_counts |  
-- | -- | -- | -- | --
1 | N/A | N/A | N/A | already have
2 | TRUE | N/A | N/A | already have
3 | FALSE | N/A | N/A | I added
4 | TRUE | TRUE | N/A | already have
5 | FALSE | TRUE | N/A | I added
6 | FALSE | FALSE | N/A | I added
7 | TRUE | FALSE | N/A |  
8 | TRUE | TRUE | TRUE | already have
9 | TRUE | TRUE | FALSE |  
10 | TRUE | FALSE | FALSE |  
11 | TRUE | FALSE | TRUE |  
12 | FALSE | TRUE | FALSE |  
13 | FALSE | TRUE | TRUE |  
14 | FALSE | FALSE | FALSE |  
15 | FALSE | FALSE | TRUE |  

However, some of them will have the same results, e.g.  | FALSE | FALSE | FALSE |  vs. | FALSE | FALSE | N/A | vs. | FALSE | N/A | N/A |  vs. | N/A | N/A | N/A | but the function definition would be different  `unique(E const &expr, std::false_type return_index, std::false_type return_inverse, std::false_type return_counts);`  vs. `unique(E const &expr, std::false_type return_index, std::false_type return_inverse);` vs.  `unique(E const &expr, std::false_type return_index);` vs. `unique(E const &expr);` . In this way, we need to support 4 functions rather than 1, is that right?

**Comment by charlotte12l** [comment]
@serge-sans-paille Now I've added support for all the possible permutations and tests, could you check if they look fine and then I can squash these commits in one?  Besides, need we also add tests for computation correctness? like the example in https://github.com/serge-sans-paille/pythran/issues/1842 :)

**Comment by serge-sans-paille** [comment]
Computation corecteness is a side effect of the test: every test tests that the return value is the same as the one from Python code, and you don't need to do anything special for that to happen. I'll have a look to the implementation.

**Comment by serge-sans-paille** [comment]
There may be room for some code syndication, but let's leave that for another commit, I'm happy with current state!

**Comment by serge-sans-paille** [comment]
Can you just squash that into a single commit please?

**Comment by charlotte12l** [comment]
@serge-sans-paille  Done :)

**Comment by serge-sans-paille** [comment]
Thanks for the hard work o/

**Pull request merged**
