### PR TITLE
General implementation of supporting immediate arguments

### PR DESCRIPTION
**Pull request by charlotte12l**
At first, I tried to use keywords name rather than offset:
```
            for k, v in node.kwargs.items():
                if k in alias.immediate_arguments:
                    if isinstance(v, ast.Constant):
                        self.result.add(v)     
```

but got the following error, saying no attribute `kwargs`, so I chose to use offset instead.
```
    def visit_Call(self, node):
        func_aliases = self.aliases[node.func]
        for alias in func_aliases:
>           for k, v in node.kwargs.items():
E           AttributeError: 'Call' object has no attribute 'kwargs'
 
pythran/analyses/immediates.py:21: AttributeError
```
 With my current offset implementation, I can pass the tests for `unique` in my local machine, but I can't pass tests for `mean` even on the master branch on my local machine:

```
------------------------------------------------ Captured stderr call -------------------------------------------------
In file included from /var/folders/j_/zm2rmlh549733gxckfkzj9000000gn/T/tmp2_dotauw.cpp:15:
In file included from /Users/charlotte/Desktop/internship/gsoc/pythran/pythran/pythonic/numpy/mean.hpp:8:
In file included from /Users/charlotte/Desktop/internship/gsoc/pythran/pythran/pythonic/numpy/sum.hpp:5:
In file included from /Users/charlotte/Desktop/internship/gsoc/pythran/pythran/pythonic/numpy/reduce.hpp:9:
In file included from /Users/charlotte/Desktop/internship/gsoc/pythran/pythran/pythonic/utils/neutral.hpp:4:
In file included from /Users/charlotte/Desktop/internship/gsoc/pythran/pythran/pythonic/include/utils/neutral.hpp:8:
In file included from /Users/charlotte/Desktop/internship/gsoc/pythran/pythran/pythonic/include/operator_/imax.hpp:5:
/Users/charlotte/Desktop/internship/gsoc/pythran/pythran/pythonic/include/numpy/maximum.hpp:9:10: fatal error: 'xsimd/xsimd.hpp' file not found
#include <xsimd/xsimd.hpp>
         ^~~~~~~~~~~~~~~~~
1 error generated.
WARNING: Compilation error, trying hard to find its origin...
WARNING: Nop, I'm going to flood you with C++ errors!
```
seems it is related to `xsimd`, do you know how to fix it?

I'll clean the code later :)

### CODE REVIEW

**Comment by charlotte12l** [comment]
@serge-sans-paille taking 4 types(`if not isinstance(alias, (ast.FunctionDef, ast.Name, ast.Call, intrinsic.UnboundValueType)):`) into consideration would pass all the checks! 

I just cleaned the code and force pushed again :)

**Comment by serge-sans-paille** [comment]
Then just `isinstance(alias, ast.expr)`

**Comment by charlotte12l** [comment]
@serge-sans-paille `if not isinstance(alias, ast.expr)` failed many checks :(

**Comment by serge-sans-paille** [comment]
> ***@***.*** if not isinstance(alias, ast.expr) failed many checks :(

what about `if not isinstance(alias, (ast.expr, ast.stmt))` ?

**Comment by charlotte12l** [comment]
> ***@***.*** if not isinstance(alias, ast.expr) failed many checks :(
> what about `if not isinstance(alias, (ast.expr, ast.stmt))` ?

Not working, failing with `AttributeError: 'UnboundValueType' object has no attribute 'immediate_arguments'` now.

**Comment by serge-sans-paille** [comment]
ok, then what about the otherway: `getattr(alias, "immediate_arguments", ())`

**Comment by charlotte12l** [comment]
@serge-sans-paille  works fine now! :)

**Comment by serge-sans-paille** [comment]
You need to rebase on master branch, can you do that?

**Comment by serge-sans-paille** [comment]
\o/

**Pull request merged**
