### PR TITLE
Add pythran option -ftime-report to print out the time spent on optim…

### PR DESCRIPTION
**Pull request by jeanlaroche**
…izations

Not sure about the way I'm printing results out (using print, perhaps logging would be more appropriate).

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Any reason why youre collecting in a dict and dumping the dict at the end, instead of just logging  within each pass?

**Comment by jeanlaroche** [comment]
> Any reason why youre collecting in a dict and dumping the dict at the end, instead of just logging within each pass?

I didn't think of reporting it right off, but I can see two reasons
- That way I cumulate the times for 2 passes of the same algo (maybe not desirable!)
- That way I can clean up the dispay (who cares?)
No good reason, I can change that if you prefer.

**Comment by serge-sans-paille** [comment]
ok, your arguments make sense. Can you update the `--help` output in docs/CLI.rst ?

**Comment by jeanlaroche** [comment]
Done

**Comment by serge-sans-paille** [comment]
Obsoleted by #1902 which is just a port + small fixes of this PR

**Pull request closed without merging**
