### PR TITLE
Pass scalar by values for user functions

### PR DESCRIPTION
**Pull request by serge-sans-paille**
passing scalar by ref (through universal reference) leads to worst code, so avoid the situation when we can.

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@jeanlaroche following up on your comments in #2095 on that PR : yeah I do plan to merge this one, but it's the most ground-breaking one, so let's dive into your issues, would you be able to share the whole error log and/or a minimal reproducer?

**Comment by jeanlaroche** [comment]
I'm confused. I haven't tried 2095, even though I commented in there... 
Should I?

And yes, I'll pasted my errors.

**Comment by jeanlaroche** [comment]
Here's the full error:

https://pastebin.com/PgjxVGrs

It's likely connected to code that I have to call a tensorflow library 
from the C++ code generated by pythran, but just in case that's not it.

Jean

**Comment by serge-sans-paille** [comment]
@jeanlaroche could you share the original python code?

**Comment by jeanlaroche** [comment]
OK I took a closer look at the code. The issue is that the calling convention used by pythran has changed with this PR so I needed to update some patches accordingly. Once I do that the compilation error disappears.

**Comment by jeanlaroche** [comment]
yes!

**Pull request merged**
