### PR TITLE
Add support for numpy.ones([...])

### PR DESCRIPTION
**Pull request by serge-sans-paille**
Turning list to tuple whenever possible does help. This is till very
naive but should handle most cases.

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@paugier can you confirm this fixes your bug?

**Comment by paugier** [comment]
No, unfortunately I cannot confirm this... But I don't think it is related to this issue and your branch default/feature/list-to-tuple.

Here, pythran crashes for changeset > 2757:24e9cfed2a21. It works with 2757:24e9cfed2a21 but not with 2758:0d0ed9ef0fec and above.

```
| @  changeset:   2758:0d0ed9ef0fec
|/   bookmark:    feature/networkx-2
|    tag:         default/feature/networkx-2
|    user:        serge-sans-paille <serge.guelton@telecom-bretagne.eu>
|    date:        Mon Sep 25 11:56:25 2017 +0200
|    summary:     Moving to networkx2
|
o    changeset:   2757:24e9cfed2a21
|\   parent:      2754:32cc332cead7
| |  parent:      2756:25b64ec82ddf
| |  user:        serge-sans-paille <serge.guelton@telecom-bretagne.eu>
| |  date:        Wed Sep 20 16:46:58 2017 +0200
| |  summary:     Merge pull request #721 from serge-sans-paille/fix/leak-tuple
```
 
With the most recent changesets, I get:

```
Traceback (most recent call last):
  File "/home/pierre/opt/mypy3/bin/pythran", line 9, in <module>
    load_entry_point('pythran==0.8.2', 'console_scripts', 'pythran')()
  File "/home/pierre/opt/mypy3/lib/python3.5/site-packages/pythran-0.8.2-py3.5.egg/pythran/run.py", line 141, in run
    **compile_flags(args))
  File "/home/pierre/opt/mypy3/lib/python3.5/site-packages/pythran-0.8.2-py3.5.egg/pythran/toolchain.py", line 387, in compile_pythranfile
    **kwargs)
  File "/home/pierre/opt/mypy3/lib/python3.5/site-packages/pythran-0.8.2-py3.5.egg/pythran/toolchain.py", line 329, in compile_pythrancode
    module, error_checker = generate_cxx(module_name, pythrancode, specs, opts)
  File "/home/pierre/opt/mypy3/lib/python3.5/site-packages/pythran-0.8.2-py3.5.egg/pythran/toolchain.py", line 131, in generate_cxx
    refine(pm, ir, optimizations)
  File "/home/pierre/opt/mypy3/lib/python3.5/site-packages/pythran-0.8.2-py3.5.egg/pythran/middlend.py", line 42, in refine
    pm.apply(FalsePolymorphism, node)
  File "/home/pierre/opt/mypy3/lib/python3.5/site-packages/pythran-0.8.2-py3.5.egg/pythran/passmanager.py", line 216, in apply
    res = a.apply(node, ctx)
  File "/home/pierre/opt/mypy3/lib/python3.5/site-packages/pythran-0.8.2-py3.5.egg/pythran/passmanager.py", line 178, in apply
    new_node = self.run(node, ctx)
  File "/home/pierre/opt/mypy3/lib/python3.5/site-packages/pythran-0.8.2-py3.5.egg/pythran/passmanager.py", line 171, in run
    n = super(Transformation, self).run(node, ctx)
  File "/home/pierre/opt/mypy3/lib/python3.5/site-packages/pythran-0.8.2-py3.5.egg/pythran/passmanager.py", line 114, in run
    return self.visit(node)
  File "/home/pierre/opt/mypy3/lib/python3.5/site-packages/pythran-0.8.2-py3.5.egg/pythran/passmanager.py", line 80, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.5/ast.py", line 300, in generic_visit
    value = self.visit(value)
  File "/home/pierre/opt/mypy3/lib/python3.5/site-packages/pythran-0.8.2-py3.5.egg/pythran/passmanager.py", line 80, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/home/pierre/opt/mypy3/lib/python3.5/site-packages/pythran-0.8.2-py3.5.egg/pythran/transformations/false_polymorphism.py", line 37, in visit_FunctionDef
    e = next(iter(udgraph.nodes))
TypeError: 'method' object is not iterable
```

Of course, I tried with networkx>=2.

**Comment by serge-sans-paille** [comment]
On Fri, Oct 13, 2017 at 01:01:56AM -0700, paugier wrote:
> No, unfortunately I cannot confirm this... But I don't think it is related to this issue and your branch default/feature/list-to-tuple.

You need to update networkx package!

pip install -U networkx

**Comment by paugier** [comment]
Arrg, it was a silly virtualenv problem, with an "old" version of decorator (4.0.11). Thank you for the hint!

I can now confirm that it works for my case. Thank you for the fix!

**Pull request merged**
