### PR TITLE
Import top-level submodules and functions lazily

### PR DESCRIPTION
**Pull request by rgommers**
This ensures that `import pythran` doesn't import a lot of code which then starts to actually do things (like trying to import numpy and scipy) which may fail or have undesirable side-effects like emitting warnings.

This should also help with Cython, which does a:
```
try:
    import pythran
except ImportError:
    pass
```
which currently yields Pythran warnings even though the user doesn't want to use Pythran but only has it installed in their environment.

In addition, it allows running `pip install -e . --no-build-isolation` in SciPy twice in a row; something that was not working before because of a recursive import issue (scipy needs pythran; pythran imports scipy).

Closes gh-2126

### CODE REVIEW

**Comment by rgommers** [comment]
CI is still chewing on it, but this looks happy now. @serge-sans-paille I had to drop Python 3.6 support, because what we need here was introduced only in Python 3.7: https://peps.python.org/pep-0562/. Since py36 and py37 are both already beyond their end-of-life date, I assume that's no problem. I noticed that Python 3.11 isn't tested at all yet, so if you want a follow-up PR for that (extending the range, or dropping Python 3.7 too), I'd be happy to do that.

**Comment by serge-sans-paille** [comment]
Super clean! Thanks. +1 for py 3.11 validation setup, thanks @rgommers

**Comment by rgommers** [comment]
> +1 for py 3.11 validation setup

Just to confirm: do you want me to just spread out the jobs a bit more across 3.7-3.11, or drop 3.7 too?

**Comment by serge-sans-paille** [comment]
> Just to confirm: do you want me to just spread out the jobs a bit more across
> 3.7-3.11, or drop 3.7 too?

Spreading.

**Pull request merged**
