### PR TITLE
Fix numpy_iexpr operator[]

### PR DESCRIPTION
**Pull request by diorcety**

### CODE REVIEW

**Comment by diorcety** [comment]
I'm not sure about that. But there is an issue if the ndarray shape size is only 1

**Comment by diorcety** [comment]
Yes

import numpy as np

#pythran export aaa(int32[][], int32[][])
def aaa(mat, mask):
    assert mask.shape == mat.shape
    mat[mask == False] = np.nan
    return mat

**Comment by serge-sans-paille** [comment]
Thanks, I can reproduce the issue and will provide a correct (^^!) fix soon.

**Comment by serge-sans-paille** [comment]
Obsoleted by #967

**Pull request closed without merging**
