### PR TITLE
Support more numpy type conversion operators

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@hroncok this should fix the i686 issue from https://src.fedoraproject.org/rpms/pythran/pull-request/1

**Comment by hroncok** [comment]
Will test tmrw.

**Comment by hroncok** [comment]
Testing with b0501d3.

**Comment by hroncok** [comment]
i686 passed.

**Comment by hroncok** [comment]
However everything other than x86 failed. See https://koji.fedoraproject.org/koji/taskinfo?taskID=39463469

**Comment by serge-sans-paille** [comment]
@hroncok you can cherry-pick 2be7a91f3d2cf9a863afeb6aae5ca20c0ca2e2c3 to fix that issue. Thanks a bunch for the follow-up

**Comment by hroncok** [comment]
This builds on all arches. Do you want to squash before I apply it in Fedora as a patch?

**Comment by serge-sans-paille** [comment]
No, that's two independent patch, you can pick them independently.

**Comment by hroncok** [comment]
Thanks.

**Comment by serge-sans-paille** [comment]
Thanks @hroncok for triggering this dev o/

**Pull request merged**
