### PR TITLE
0.17.0 - bara pok ha pok

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
cc @rgommers @stefanv @jeanlaroche @hroncok @ h-vetinari

**Comment by h-vetinari** [comment]
Looks alright in https://github.com/conda-forge/pythran-feedstock/pull/89

**Comment by serge-sans-paille** [comment]
@hroncok : I'll merge once I have your green light. Historically you've been the one that challenges pythran codebase the most :-)

**Comment by hroncok** [comment]
I wasn't able to get to pythran in Fedora lately. I'll do my best to twst this release during the weekend.

**Comment by hroncok** [comment]
I finally needed to update gast and beniget -- this will be done together with pythran.

Hence, everything is prepared in this copr: https://copr.fedorainfracloud.org/coprs/churchyard/pythran-0.17/builds/

pythran build starts

**Comment by hroncok** [comment]
82 tests fails with

```
/usr/bin/ld: cannot find -lopenblas: No such file or directory
collect2: error: ld returned 1 exit status
```

We depend on flexiblas-devel. No idea what's going on.

One is (similar?):

```
/builddir/build/BUILD/pythran-0.17.0-build/BUILDROOT/usr/lib/python3.13/site-packages/pythran/pythonic/numpy/dot.hpp:1299:10: fatal error: cblas.h: No such file or directory
 1299 | #include <cblas.h>
      |          ^~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```

The last one is TestDoctest.test_tutorial from https://github.com/serge-sans-paille/pythran/issues/2214 (still).

That is on x86_64.

**Comment by serge-sans-paille** [comment]
@hroncok : I think that changing

https://src.fedoraproject.org/rpms/pythran/blob/rawhide/f/pythran.spec#_71

to `sed -i 's|blas=blas|blas=flexiblas|' pythran/pythran-linux*.cfg`

and removing https://src.fedoraproject.org/rpms/pythran/blob/rawhide/f/pythran.spec#_72

will work. At least it does on my setup.

**Comment by hroncok** [comment]
That indeed solved the 82 failures. No idea why it worked the way it was in the past... anyway, this one remains:

```
=================================== FAILURES ===================================
__________________________ TestMeson.test_meson_build __________________________
[gw2] linux -- Python 3.13.0 /usr/bin/python3

self = <pythran.tests.test_distutils.TestMeson testMethod=test_meson_build>

    @unittest.skipIf(not has_meson, "meson not found")
    @unittest.skipIf(not has_ninja, "ninja not found")
    def test_meson_build(self):
        srcdir = os.path.join(cwd, 'test_distutils')
        builddir = os.path.join(srcdir, '_meson_build')
        shutil.rmtree(builddir, ignore_errors=True)
        check_call(['meson', 'setup', builddir, '.'],
                   cwd=srcdir)
>       check_call(['ninja', '-v'],
                   cwd=builddir)

pythran/tests/test_distutils.py:196: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['ninja', '-v'],)
kwargs = {'cwd': '/builddir/build/BUILD/pythran-0.17.0-build/pythran-release-0.17/pythran/tests/test_distutils/_meson_build'}
retcode = 1, cmd = ['ninja', '-v']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

/usr/lib64/python3.13/subprocess.py:419: CalledProcessError
----------------------------- Captured stdout call -----------------------------
The Meson build system
Version: 1.5.1
Source dir: /builddir/build/BUILD/pythran-0.17.0-build/pythran-release-0.17/pythran/tests/test_distutils
Build dir: /builddir/build/BUILD/pythran-0.17.0-build/pythran-release-0.17/pythran/tests/test_distutils/_meson_build
Build type: native build
Project name: pythran-test
Project version: undefined
C++ compiler for the host machine: g++ (gcc 14.2.1 "g++ (GCC) 14.2.1 20240912 (Red Hat 14.2.1-4)")
C++ linker for the host machine: g++ ld.bfd 2.43.50.20241014
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 (pythran) found: YES (/usr/bin/python3) modules: pythran
Found pkg-config: YES (/usr/bin/pkg-config) 2.3.0
Run-time dependency python found: YES 3.13
Build targets in project: 2

Found ninja-1.12.1 at /usr/bin/ninja
[1/3] env PYTHRANRC=/builddir/build/BUILD/pythran-0.17.0-build/pythran-release-0.17/pythran/tests/test_distutils/pythran.rc /usr/bin/python3 -m pythran.run -E ../b.py -o b.cpp
[2/3] g++ -Ib.cpython-313-x86_64-linux-gnu.so.p -I. -I.. -I/usr/include/openblas -I/builddir/build/BUILD/pythran-0.17.0-build/BUILDROOT/usr/lib/python3.13/site-packages/pythran -I/usr/lib64/python3.13/site-packages/numpy/core/include -I/usr/include/python3.13 -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DPYTHRAN_BLAS_OPENBLAS -MD -MQ b.cpython-313-x86_64-linux-gnu.so.p/meson-generated_.._b.cpp.o -MF b.cpython-313-x86_64-linux-gnu.so.p/meson-generated_.._b.cpp.o.d -o b.cpython-313-x86_64-linux-gnu.so.p/meson-generated_.._b.cpp.o -c b.cpp
FAILED: b.cpython-313-x86_64-linux-gnu.so.p/meson-generated_.._b.cpp.o 
g++ -Ib.cpython-313-x86_64-linux-gnu.so.p -I. -I.. -I/usr/include/openblas -I/builddir/build/BUILD/pythran-0.17.0-build/BUILDROOT/usr/lib/python3.13/site-packages/pythran -I/usr/lib64/python3.13/site-packages/numpy/core/include -I/usr/include/python3.13 -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DPYTHRAN_BLAS_OPENBLAS -MD -MQ b.cpython-313-x86_64-linux-gnu.so.p/meson-generated_.._b.cpp.o -MF b.cpython-313-x86_64-linux-gnu.so.p/meson-generated_.._b.cpp.o.d -o b.cpython-313-x86_64-linux-gnu.so.p/meson-generated_.._b.cpp.o -c b.cpp
In file included from /builddir/build/BUILD/pythran-0.17.0-build/BUILDROOT/usr/lib/python3.13/site-packages/pythran/pythonic/operator_/matmul.hpp:6,
                 from b.cpp:15:
/builddir/build/BUILD/pythran-0.17.0-build/BUILDROOT/usr/lib/python3.13/site-packages/pythran/pythonic/numpy/dot.hpp:1299:10: fatal error: cblas.h: No such file or directory
 1299 | #include <cblas.h>
      |          ^~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```

**Comment by hroncok** [comment]
But `/usr/include/flexiblas/cblas.h` exists.

**Comment by rgommers** [comment]
> But `/usr/include/flexiblas/cblas.h` exists.

The build command includes `-I/usr/include/openblas`, not `-I/usr/include/flexiblas`. So `blas=flexiblas` doesn't seem to have the intended effect for you.

**Comment by hroncok** [comment]
We have `include_dirs=/usr/include/flexiblas` in pythran-linux*.cfg

**Comment by serge-sans-paille** [comment]
@hroncok did you remove https://src.fedoraproject.org/rpms/pythran/blob/rawhide/f/pythran.spec#_73 ?

**Comment by hroncok** [comment]
> @hroncok did you remove https://src.fedoraproject.org/rpms/pythran/blob/rawhide/f/pythran.spec#_73 ?

No. This build is with:

```
# Use FlexiBLAS
sed -i 's|blas=blas|blas=flexiblas|' pythran/pythran-linux*.cfg
sed -i 's|include_dirs=|include_dirs=/usr/include/flexiblas|' pythran/pythran-linux*.cfg
```

**Comment by hroncok** [comment]
And pythran/pythran-linux*.cfg is:

```
[compiler]
defines=
undefs=
include_dirs=/usr/include/flexiblas
libs=
library_dirs=
cflags=-std=c++11 -fno-math-errno -fvisibility=hidden -fno-wrapv -Wno-unused-function -Wno-int-in-bool-context -Wno-unknown-warning-option
ldflags=-fvisibility=hidden -Wl,-strip-all
blas=flexiblas
CC=
CXX=
ignoreflags=-Wstrict-prototypes
```

**Comment by serge-sans-paille** [comment]
@hroncok this test tests openblas integration, under the assumption it's installed. You can modify `pythran/tests/test_distutils/pythran.rc` to point at flexiblas, or just ignore it.

**Comment by hroncok** [comment]
build passed, thanks for all the help.

will submit Fedora dependents

**Comment by hroncok** [comment]
I realized now scipy pins older pythran. I relaxed the pin and trying to build scipy agian.

**Comment by hroncok** [comment]
All is good. Thanks for the heads up and help!

**Comment by serge-sans-paille** [comment]
It's out! https://pypi.org/project/pythran/0.17.0

**Comment by hroncok** [comment]
Please push a tag to GitHub as well.

**Comment by serge-sans-paille** [comment]
fait!

**Comment by hroncok** [comment]
A real Fedora build in https://koji.fedoraproject.org/koji/taskinfo?taskID=125394077

**Comment by hroncok** [comment]
Fedora 42 update: https://bodhi.fedoraproject.org/updates/FEDORA-2024-7665f7f7e2

**Pull request merged**
