### PR TITLE
Make arange a lazy expression

### PR DESCRIPTION
**Pull request by serge-sans-paille**
This speedsup expression like ``np.arange(x) * y``.

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Fixes #1114, and that should be a performance improvment for @jeanlaroche !

**Comment by jeanlaroche** [comment]
Awesome, let me grab, and retest!

**Comment by jeanlaroche** [comment]
I get a compilation error using the new branch but not with master.
Source code: https://pastebin.com/m89JeBzb

Error:
https://pastebin.com/LG0Dk2jD

I didn't do a python setup.py -install. Is that necessary here?

**Comment by serge-sans-paille** [comment]
@jeanlaroche better now?

**Comment by jeanlaroche** [comment]
WOn't be able to check until monday, but I trust you! :)

**Pull request merged**
