### PR TITLE
Remote/diorcety/import

### PR DESCRIPTION
**Pull request by serge-sans-paille**
Inspired by #835

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@diorcety does that sounds ok to you?

**Comment by diorcety** [comment]
Except the OpenMP stuff from my comment, it works well. I'm currently using it :)

**Comment by serge-sans-paille** [comment]
@diorcety better like this?

**Comment by diorcety** [comment]
Nope. I'm made the same mistake. I still have the issue if ExtractDocStrings is before GatherOMPData

**Comment by serge-sans-paille** [comment]
Better now?

**Comment by diorcety** [comment]
Yes !

**Pull request merged**
