### PR TITLE
Improve portability on 32 bit platform

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by hroncok** [comment]
## i686

```
+ /usr/bin/python3 -m pytest -n auto -k 'not test_zig_zag_matrix_run1'
============================= test session starts ==============================
platform linux -- Python 3.7.4rc2, pytest-4.4.1, py-1.8.0, pluggy-0.12.0
rootdir: /builddir/build/BUILD/pythran-fix-32-bit-port
plugins: xdist-1.29.0, forked-1.0.2
gw0 I / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / gw7 I / gw8 I / gw9 I / gw10 I / gw11 I / gw12 I / gw13 I / gw14 I / gw15 I / gw16 I / gw17 I / gw18 I / gw19 I / gw20 I / gw21 I / gw22 I / gw23 I / gw24 I / gw25 I / gw26 I / gw27 I / gw28 I / gw29 I / gw30 I / gw31 I / gw32 I / gw33 I / gw34 I / gw35 I / gw36 I / gw37 I / gw38 I / gw39 I / gw40 I / gw41 I / gw42 I / gw43 I / gw44 I / gw45 I / gw46 I / gw47 I
gw0 [3025] / gw1 [3025] / gw2 [3025] / gw3 [3025] / gw4 [3025] / gw5 [3025] / gw6 [3025] / gw7 [3025] / gw8 [3025] / gw9 [3025] / gw10 [3025] / gw11 [3025] / gw12 [3025] / gw13 [3025] / gw14 [3025] / gw15 [3025] / gw16 [3025] / gw17 [3025] / gw18 [3025] / gw19 [3025] / gw20 [3025] / gw21 [3025] / gw22 [3025] / gw23 [3025] / gw24 [3025] / gw25 [3025] / gw26 [3025] / gw27 [3025] / gw28 [3025] / gw29 [3025] / gw30 [3025] / gw31 [3025] / gw32 [3025] / gw33 [3025] / gw34 [3025] / gw35 [3025] / gw36 [3025] / gw37 [3025] / gw38 [3025] / gw39 [3025] / gw40 [3025] / gw41 [3025] / gw42 [3025] / gw43 [3025] / gw44 [3025] / gw45 [3025] / gw46 [3025] / gw47 [3025]
sss................................s.........................s............ [  2%]
....................................................s......s............ [  4%]
........................................................................ [  7%]
...........................................................F............ [  9%]
.......s..................................s............ss....s......ss.. [ 11%]
s.s........s...............................................s............ [ 14%]
.........s...........s.......s.....ssssssssss.ssss.....................s [ 16%]
....ss..............s...s....s...s............s.........s....s.......... [ 19%]
s........ss.s.............s..s.............s..................ss........ [ 21%]
.....s..............ss......Fsss........F.........s..................... [ 23%]
................................F.............sss....................... [ 26%]
.F......................F...ss...............................F.......... [ 28%]
..............................F.............F............F.....s........ [ 31%]
.F...................F..........................F.s.s....ss.FF......s... [ 33%]
.....................s.......F...F..........s....F...................... [ 35%]
.....F....F..F.............................F.............F.F.....F.F.... [ 38%]
............F........F..........F...F...........ss................F..... [ 40%]
.........F...............................F...FF......................... [ 42%]
............s....FF..........................F....................F.F... [ 45%]
..................s.............s.................................F..... [ 47%]
....FsF....F........F...............F....F........F..F..........FF..F... [ 50%]
.......................F....................F........F..F............... [ 52%]
..F................F.F................F...................F............. [ 54%]
.....F...F............F.......................................F......... [ 57%]
..............F................s..F..................................... [ 59%]
...F........................................................F........... [ 61%]
..................................F....................................F [ 64%]
................................F...................................s... [ 66%]
.F...................................................F.................. [ 69%]
........................................................................ [ 71%]
........................................................................ [ 73%]
........................................................................ [ 76%]
......Fs..............s....F............................................ [ 78%]
...............sss..........................................s........... [ 80%]
.......................................................................s [ 83%]
.................................................................s...... [ 85%]
...............................s..........................ss...F........ [ 88%]
....s......s.s...s...................................................... [ 90%]
.......................................................s..s............. [ 92%]
..s.s................................................................... [ 95%]
........................................................................ [ 97%]
.......................................................................  [100%]
===== 77 failed, 2847 passed, 101 skipped, 191 warnings in 507.33 seconds ======
```

[i686.build.log](https://github.com/serge-sans-paille/pythran/files/3389984/i686.build.log)

**Comment by hroncok** [comment]
## armv7hl

```
+ /usr/bin/python3 -m pytest -n auto -k 'not test_zig_zag_matrix_run1'
============================= test session starts ==============================
platform linux -- Python 3.7.4rc2, pytest-4.4.1, py-1.8.0, pluggy-0.12.0
rootdir: /builddir/build/BUILD/pythran-fix-32-bit-port
plugins: forked-1.0.2, xdist-1.29.0
gw0 I / gw1 I / gw2 I / gw3 I
gw0 [3025] / gw1 [3025] / gw2 [3025] / gw3 [3025]
.........................ss......s...................................... [  2%]
..............s................s......................................s. [  4%]
.....s.................................................................. [  7%]
.............................................................F.......... [  9%]
....................s.................s............................s..s. [ 11%]
................................ss....................ss................ [ 14%]
.s....................s.s.................s..s.s........................ [ 16%]
......................................s.......s..s...s..s.......s....s.. [ 19%]
s......s............s................................................... [ 21%]
......s................s....s......s....F..F................F........... [ 23%]
.......F..F........F..............F..F.................F..............ss [ 26%]
.........................................F..............s....F...F...... [ 28%]
........................s.......s......................F..F...F...F.ss.. [ 30%]
F................ssssssssssssssss...........s.......ss................ss [ 33%]
ss..s...................................FF..FF...F....F...F..F.......... [ 35%]
........................................................................ [ 38%]
.................sss......................ss......................F...F. [ 40%]
.....................................................................F.. [ 42%]
..............F...........F............................F..F............F [ 45%]
......s.F....F....F...F..F............F..............F..F..F.........F.. [ 47%]
.......F.............F.....F..FF..F................ss.s.Fsss.Fs..F....ss [ 49%]
s.....F....................F............................................ [ 52%]
..........................F..F...F...................................... [ 54%]
................................F..FF..F......F..F...................... [ 57%]
........................................................................ [ 59%]
........................................F.......F......F...F............ [ 61%]
...F.........F..........F.....F......................................... [ 64%]
........................................................................ [ 66%]
..........F............................................................. [ 69%]
......................................................................F. [ 71%]
................................................................F....... [ 73%]
.....................................................................F.. [ 76%]
........................................................................ [ 78%]
........................................................................ [ 80%]
sss.......................................s............................. [ 83%]
.............s.......................................................... [ 85%]
............s...............................s........................... [ 88%]
................s....................s.................................. [ 90%]
..........s.................F........s..s............................... [ 92%]
...........................ss............s..............ss.............. [ 95%]
..........................s...............................s............. [ 97%]
........................................................................ [ 99%]
.                                                                        [100%]
===== 77 failed, 2847 passed, 101 skipped, 103 warnings in 9805.49 seconds =====
```

[armv7hl.build.log](https://github.com/serge-sans-paille/pythran/files/3390323/armv7hl.build.log)

**Comment by serge-sans-paille** [comment]
@hroncok thansk! We did decrease the number of fails, what about now?

**Comment by hroncok** [comment]
Build runs at: https://koji.fedoraproject.org/koji/taskinfo?taskID=36519075 (I'll copy the results once it is ready)

**Comment by hroncok** [comment]
## i686

```
+ /usr/bin/python3 -m pytest -n auto -k 'not test_zig_zag_matrix_run1'
============================= test session starts ==============================
platform linux -- Python 3.7.4, pytest-4.6.4, py-1.8.0, pluggy-0.12.0
rootdir: /builddir/build/BUILD/pythran-fix-32-bit-port
plugins: xdist-1.29.0, forked-1.0.2
gw0 I / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I
gw0 [3025] / gw1 [3025] / gw2 [3025] / gw3 [3025] / gw4 [3025] / gw5 [3025]
.............s..............s.s......................................... [  2%]
....s.............................s............................s........ [  4%]
..s..................................................................... [  7%]
..............................................................F......... [  9%]
....................s.........................s......................... [ 11%]
....s...s................s.........s..s......s.......................... [ 14%]
.........s...............s..s.................................s...s..... [ 16%]
.....s......s.s....s.................s..s.s..........s...s.............. [ 19%]
........................ss..........................s..........s........ [ 21%]
..ssssssssssssssss.......s....s...s..s........ss...........s......ssss.. [ 23%]
...s......................s...s..................s.s.................... [ 26%]
.....s........................................................ss......ss [ 28%]
s...........sss......................................................... [ 30%]
........................................................................ [ 33%]
........................................................................ [ 35%]
....................................F....F.............................. [ 38%]
........................................................................ [ 40%]
.......................................................s.......sss...... [ 42%]
.......................ss............................................... [ 45%]
........................................................................ [ 47%]
........................................................................ [ 49%]
....................................................s......s............ [ 52%]
F..F..F................................................................. [ 54%]
........................................................................ [ 57%]
........................................................................ [ 59%]
..................................F....F......F.....F..........F.....F.. [ 61%]
........................................................................ [ 64%]
........................................................................ [ 66%]
........................F..............F...............F................ [ 69%]
.................................................F........F............. [ 71%]
..........F............................................................. [ 73%]
......................................................F................. [ 76%]
........................................................................ [ 78%]
........................................................................ [ 80%]
.........s......................s....................................... [ 83%]
.........................s.....................sss.......s.............. [ 85%]
..........................................s............................. [ 88%]
...s............................s.......................F............... [ 90%]
.s....s...................s............................................. [ 92%]
.........................................ss.........ss.................. [ 95%]
.................s...................................................... [ 97%]
...................................................................s.... [ 99%]
.                                                                        [100%]
===== 20 failed, 2904 passed, 101 skipped, 113 warnings in 2075.53 seconds =====
```

[i686.build.log](https://github.com/serge-sans-paille/pythran/files/3433418/i686.build.log)

**Comment by hroncok** [comment]
## arm7hl

```
==== 20 failed, 2904 passed, 101 skipped, 107 warnings in 18480.47 seconds =====
```

[arm7hl.build.log](https://github.com/serge-sans-paille/pythran/files/3433560/arm7hl.build.log)

**Comment by serge-sans-paille** [comment]
Thanks @hroncok. I had a look to all test case and I think we can blacklist them for i686. I can do it at unittest level, it's probably better than doing it in the spec file?

**Comment by hroncok** [comment]
Sure. I still fail to understand the failures there.

**Comment by serge-sans-paille** [comment]
> I still fail to understand the failures there.

A few are related to FP accuracy, but most of them are related to the fact that pythran generates an int instead of a numpy.int32 in some situations :-/

**Comment by hroncok** [comment]
The accuracy make sense, but the occasional `int` instead of `numpy.int32` surprised me, I thought that those are the same on 32bit.

**Comment by serge-sans-paille** [comment]
@hroncok just uploaded a version with more permissive testing, /me crosses finger

**Comment by serge-sans-paille** [comment]
Only one remaining fail: https://kojipkgs.fedoraproject.org//work/tasks/15/36670015/build.log

**Comment by serge-sans-paille** [comment]
https://koji.fedoraproject.org/koji/taskinfo?taskID=36671965 looks good now \o/ thanks a lot @hroncok for triggering this dev.

**Pull request merged**
