### PR TITLE
Feature/pip

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@pbrunet: can you review this one? It incorporates most of my previous work on setuptools support, without the windows part.

Validation is ok on my laptop.

**Comment by pbrunet** [comment]
@serge-sans-paille Ok, I will look at this tomorow.
The previous PR is "ready" too. It is not OK for windows (missing blas, missing appveyor and some others) but it fix many issues and works on linux as expected.
The other PR also fix .travis.yml file (because travis didn't run anymore on the current .travis.yml file) (--user not required)

**Comment by serge-sans-paille** [comment]
@pbrunet #469 is too big to be reviewed, that's why I splited it here. +1 for the travis switch.

**Comment by pbrunet** [comment]
"Restore  clean state for nt2" and "better nt2 configure ..." could be merge

**Comment by pbrunet** [comment]
commit 3d2f729b744d03881d4be008d2957bc7ea400788 : Some duplicate test name fixed.
commit 3cf3e297543c9ce06f75846eec926b8d11f3ff7f : Fix de travix.yml

**Comment by pbrunet** [comment]
commit 542b2ed41dd9e8f3b6110a574512dbf1c09621dc: PEP8 check
commit 718950add77aaa4a719d457e80da41fd01ba0774 : docstring check `pythran.__init__.py`
commit 545409d431bc7972c453410abc34ed68ef68be42 : No check for paper folder

**Comment by serge-sans-paille** [comment]
On Mon, Aug 10, 2015 at 01:41:16AM -0700, pbrunet wrote:
> commit 542b2ed41dd9e8f3b6110a574512dbf1c09621dc: PEP8 check
> commit 718950add77aaa4a719d457e80da41fd01ba0774 : docstring check `pythran.__init__.py`
> commit 545409d431bc7972c453410abc34ed68ef68be42 : No check for paper folder

Done. I already reproduced 718950add77aaa4a719d457e80da41fd01ba0774 with
a SG flavor :-)

**Comment by serge-sans-paille** [comment]
On Mon, Aug 10, 2015 at 01:39:02AM -0700, pbrunet wrote:
> commit 3d2f729b744d03881d4be008d2957bc7ea400788 : Some duplicate test name fixed.

I could not find this one

> commit 3cf3e297543c9ce06f75846eec926b8d11f3ff7f : Fix de travix.yml

ok for this one

**Comment by serge-sans-paille** [comment]
@pbrunet validation is ok on my laptop now, thanks for the proofreading!

**Comment by serge-sans-paille** [comment]
@pbrunet: should be OK now, travis thinks so too. Thanks *a lot* for spotting the many issues in there.

**Pull request merged**
