### PR TITLE
Feature/decl impl

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@pbrunet : i'll finish the rebase, there a few conflicts

**Comment by serge-sans-paille** [comment]
looks good to travis!

**Comment by pbrunet** [comment]
Can I just merge it? (they are my commits so ....)

**Comment by serge-sans-paille** [comment]
On Sun, Apr 26, 2015 at 07:13:56AM -0700, pbrunet wrote:
> Can I just merge it? (they are my commits so ....)

yes :-)

**Pull request merged**
