### PR TITLE
Improve constant folding

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
cc @jeanlaroche can you check this one on your codebase? It's some extra speedup but it's quite a huge change

**Comment by serge-sans-paille** [comment]
cc @rgommers / @stefanv  can you give it a shot on your respective codebase?

**Comment by serge-sans-paille** [comment]
Thanks @rgommers for spotting this. Better now?

**Comment by rgommers** [comment]
Yep, all good now on macOS too.

**Comment by serge-sans-paille** [comment]
Thanks @rgommers . @jeanlaroche ?

**Pull request merged**
