### PR TITLE
Bugfix/fast and correct itertools combinations

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Apart from the pep8 update, this PR is ok for review.

**Comment by serge-sans-paille** [comment]
Updated & rebased, let see what travis thinks of this

**Comment by pbrunet** [comment]
What about std::move when we return?
There was a discussion with @joker-eph on IRC about it and he said we could break RVO optimisation doing this but I am not confortable enough with this to make a decision.
@jfalcou can you explain why it is so bad compare to rewriting the full (long ...) type?

**Comment by serge-sans-paille** [comment]
travis loves me <3

**Comment by serge-sans-paille** [comment]
we have this constructor. ready to merge?

**Comment by pbrunet** [comment]
I don't understand :-$

**Comment by serge-sans-paille** [comment]
:-) @jfalcou said it's ok to use the move constructor that way ;-)

**Comment by serge-sans-paille** [comment]
@pbrunet I updated the move constructor

**Comment by pbrunet** [comment]
It was manually merged

**Pull request closed without merging**
