### PR TITLE
Do not remove a package from supported package when it's not available

### PR DESCRIPTION
**Pull request by serge-sans-paille**
Instead, use a degraded mode where introspection cannot be used and constant
folding is disabled for the functions in that package.

### CODE REVIEW

**Comment by rgommers** [comment]
Naive question: what's the practical implication of this? Just a little bit of performance, right?

**Comment by serge-sans-paille** [comment]
On Fri, Jun 18, 2021 at 01:29:38AM -0700, Ralf Gommers wrote:
> Naive question: what's the practical implication of this? Just a little bit of
> performance, right?

less performance if the function is called with constant arguments (no constant folding)
no support for keyword arguments for these functions (no introspection)

**Comment by rgommers** [comment]
Looks like that did the trick! Making the warning appear only once per module would be great, because there's a lot of this now in the build log:
```
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
```

<details>

```
$ python setup.py build_ext -i
Running from SciPy source directory.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
Cythonizing sources
Running scipy/linalg/_generate_pyx.py
Running scipy/stats/_generate_pyx.py
Running scipy/special/_generate_pyx.py
Processing scipy/linalg/_matfuncs_sqrtm_triu.pyx
Processing scipy/linalg/cython_blas.pyx
Processing scipy/spatial/transform/rotation.pyx
Processing scipy/linalg/cython_lapack.pyx
Processing scipy/linalg/_decomp_update.pyx.in
Processing scipy/fftpack/convolve.pyx
Processing scipy/_lib/messagestream.pyx
Processing scipy/_lib/_test_deprecation_def.pyx
Processing scipy/_lib/_ccallback_c.pyx
Processing scipy/_lib/_test_deprecation_call.pyx
Processing scipy/spatial/ckdtree.pyx
Processing scipy/spatial/qhull.pyx
Processing scipy/spatial/_voronoi.pyx
Processing scipy/spatial/_hausdorff.pyx
Processing scipy/linalg/_solve_toeplitz.pyx
Processing scipy/stats/_stats.pyx
Processing scipy/stats/_qmc_cy.pyx
Processing scipy/stats/_sobol.pyx
Processing scipy/stats/biasedurn.pyx
Processing scipy/stats/_boost/src/binom_ufunc.pyx
Processing scipy/stats/_boost/src/beta_ufunc.pyx
Processing scipy/stats/_boost/src/nbinom_ufunc.pyx
Processing scipy/stats/_boost/src/hypergeom_ufunc.pyx
Processing scipy/special/_ufuncs.pyx
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
Processing scipy/special/_comb.pyx
Processing scipy/special/_ellip_harm_2.pyx
Processing scipy/special/cython_special.pyx
Processing scipy/special/_test_round.pyx
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
Processing scipy/special/_ufuncs_cxx.pyx
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
Processing scipy/io/matlab/mio_utils.pyx
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
Processing scipy/io/matlab/mio5_utils.pyx
Processing scipy/io/matlab/streams.pyx
Processing scipy/interpolate/_bspl.pyx
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
Processing scipy/interpolate/_ppoly.pyx
Processing scipy/interpolate/interpnd.pyx
Processing scipy/signal/_sosfilt.pyx
Processing scipy/signal/_upfirdn_apply.pyx
Processing scipy/signal/_peak_finding_utils.pyx
Processing scipy/signal/_spectral.pyx
Processing scipy/signal/_max_len_seq_inner.pyx
Processing scipy/cluster/_hierarchy.pyx
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
Processing scipy/cluster/_vq.pyx
Processing scipy/cluster/_optimal_leaf_ordering.pyx
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
Processing scipy/optimize/_group_columns.pyx
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
Processing scipy/optimize/_bglu_dense.pyx
Processing scipy/optimize/_lsq/givens_elimination.pyx
Processing scipy/optimize/cython_optimize/_zeros.pyx.in
Processing scipy/optimize/_trlib/_trlib.pyx
Processing scipy/optimize/_highs/cython/src/_highs_wrapper.pyx
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
Processing scipy/optimize/_highs/cython/src/_highs_constants.pyx
Processing scipy/ndimage/src/_cytest.pyx
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
Processing scipy/ndimage/src/_ni_label.pyx
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
Processing scipy/sparse/_csparsetools.pyx.in
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
Processing scipy/sparse/csgraph/_flow.pyx
Processing scipy/sparse/csgraph/_reordering.pyx
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
Processing scipy/sparse/csgraph/_tools.pyx
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
Processing scipy/sparse/csgraph/_traversal.pyx
Processing scipy/sparse/csgraph/_min_spanning_tree.pyx
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
Processing scipy/sparse/csgraph/_shortest_path.pyx
Processing scipy/sparse/csgraph/_matching.pyx
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy' will be reduced: this module is not available at runtime.
WARNING: Pythran support for package 'scipy.special' will be reduced: this module is not available at runtime.
...
```

</details>

**Comment by rgommers** [comment]
+1 for merging this as is and dealing with the repeated warnings at some other time though, if that's easier. fixing the build error will unblock @charlotte12l's work in her `pythran_count` branch.

**Comment by serge-sans-paille** [comment]
> Looks like that did the trick! Making the warning appear only once per module would be great, because there's a lot of this now in the build log:

it should only happens once per process—it happens on module load afterall. Are we running each build in a separate process or something?

**Comment by rgommers** [comment]
Ah yes, that makes it hard to reduce the noise. I'm guessing we do. And certainly when moving to parallel builds we will be running in separate processes. That means it's not fixable, except for a command line flag to control the warning level from `info` to `debug` or something like that.

**Pull request merged**
