### PR TITLE
Fix several testing issues on m32 architectures

### PR DESCRIPTION
**Pull request by serge-sans-paille**
- Do not overflow using 2**32
- Be explicit about array type

This is a partial fix for #1639

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
With these two commits, let's hope #1639 gets fixed, cc @hroncok

**Comment by hroncok** [comment]
https://koji.fedoraproject.org/koji/taskinfo?taskID=51544810

**Comment by hroncok** [comment]
On all arches:

    pythran.syntax.PythranSyntaxError: identifier int8 unknown, either because it is an unsupported intrinsic, the input code is faulty, or... pythran is buggy.

Plus on i686:

```
________________________ TestCases.test__histogram_run0 ________________________
[gw3] linux -- Python 3.9.0 /usr/bin/python3
self = <pythran.tests.TestFromDir.TestFunctor object at 0xea47d148>
    def __call__(self):
        if "unittest.skip" in self.module_code:
            return self.test_env.skipTest("Marked as skippable")
    
        if "unittest.python3.skip" in self.module_code:
            return self.test_env.skipTest("Marked as skippable")
    
        # resolve import locally to where the tests are located
        sys.path.insert(0, self.test_env.path)
    
>       self.test_env.run_test_case(self.module_code, self.module_name,
                                    self.runas, module_dir=self.module_dir,
                                    **self.specs)
pythran/tests/__init__.py:454: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pythran/tests/__init__.py:262: in run_test_case
    self.assertAlmostEqual(python_ref, pythran_res)
pythran/tests/__init__.py:119: in assertAlmostEqual
    self.assertAlmostEqual(ref_v, res_v)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <pythran.tests.test_cases.TestCases testMethod=test__histogram_run0>
ref = array([1., 1., 2.], dtype=float32)
res = array([0., 0., 0.], dtype=float32)
    def assertAlmostEqual(self, ref, res):
        """
        Improved version of assertAlmostEqual.
    
        This new version supports nan, complex and ndarray.
        """
        self.check_type(ref, res)
        if isinstance(res, (list, tuple)):
            self.assertEqual(len(res), len(ref))
            for res_v, ref_v in zip(res, ref):
                self.assertAlmostEqual(ref_v, res_v)
        elif isinstance(ref, ndarray):
>           npt.assert_array_almost_equal(ref, res)
E           AssertionError: 
E           Arrays are not almost equal to 6 decimals
E           
E           Mismatched elements: 3 / 3 (100%)
E           Max absolute difference: 2.
E           Max relative difference: inf
E            x: array([1., 1., 2.], dtype=float32)
E            y: array([0., 0., 0.], dtype=float32)
pythran/tests/__init__.py:121: AssertionError
------------------------------ Captured log setup ------------------------------
WARNING  root:spec.py:94 No pythran specification, nothing will be exported
----------------------------- Captured stdout call -----------------------------
Python result:  (array([1., 1., 2.], dtype=float32), array([0., 1., 2., 3.], dtype=float32))
Pythran result:  (array([0., 0., 0.], dtype=float32), array([0., 1., 2., 3.], dtype=float32))
Type of Pythran res :  <class 'tuple'>
Type of Python ref :  <class 'tuple'>
Type of Pythran res :  <class 'numpy.ndarray'>
Type of Python ref :  <class 'numpy.ndarray'>
```

and

```
_____________________ TestNumpyRandom.test_numpy_laplace0b _____________________
[gw3] linux -- Python 3.9.0 /usr/bin/python3
self = <pythran.tests.test_numpy_random.TestNumpyRandom testMethod=test_numpy_laplace0b>
    def test_numpy_laplace0b(self):
        """ Check laplace with 2 argument with mean and variance. """
        code = """
        def numpy_laplace0b(size):
            from numpy.random import laplace
            from numpy import var, mean, pi
            u = 2.
            s = 2
            rmean = u
            rvar = 2*s**2
            a = laplace(u, s, size)
            return (abs(mean(a) - rmean) < 0.05 and abs(var(a) - rvar) < .05)
        """
>       self.run_test(code, 10 ** 6, numpy_laplace0b=[int])
pythran/tests/test_numpy_random.py:1480: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pythran/tests/__init__.py:318: in run_test
    self.assertAlmostEqual(python_ref, pythran_res)
pythran/tests/__init__.py:144: in assertAlmostEqual
    self.assertEqual(ref, res)
E   AssertionError: True != False
----------------------------- Captured stdout call -----------------------------
Python result:  True
Pythran result:  False
Type of Pythran res :  <class 'bool'>
Type of Python ref :  <class 'numpy.bool_'>
```

**Comment by serge-sans-paille** [comment]
Last bug fixed, or so i hope :-)

**Comment by hroncok** [comment]
https://koji.fedoraproject.org/koji/taskinfo?taskID=51574046

**Comment by hroncok** [comment]
64bits:

```
_________________________ TestNumpyFunc2.test_asarray5 _________________________
[gw1] linux -- Python 3.9.0 /usr/bin/python3
self = <pythran.tests.test_numpy_func2.TestNumpyFunc2 testMethod=test_asarray5>
    def test_asarray5(self):
>       self.run_test("def np_asarray5(a):\n from numpy import asarray, int8\n return asarray(a, dtype=int8)", 1, np_asarray5=[int])
pythran/tests/test_numpy_func2.py:494: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pythran/tests/__init__.py:318: in run_test
    self.assertAlmostEqual(python_ref, pythran_res)
pythran/tests/__init__.py:115: in assertAlmostEqual
    self.check_type(ref, res)
pythran/tests/__init__.py:91: in check_type
    self.check_type(ref.item(0), res)
pythran/tests/__init__.py:107: in check_type
    self.assertIsInstance(res, type(ref))
E   AssertionError: 1 is not an instance of <class 'int'>
----------------------------- Captured stdout call -----------------------------
Python result:  1
Pythran result:  1
Type of Pythran res :  <class 'numpy.int8'>
Type of Python ref :  <class 'numpy.ndarray'>
Type of Pythran res :  <class 'numpy.int8'>
Type of Python ref :  <class 'int'>
```

**Comment by serge-sans-paille** [comment]
updated!

**Comment by hroncok** [comment]
https://koji.fedoraproject.org/koji/taskinfo?taskID=51591592

**Comment by hroncok** [comment]
https://koji.fedoraproject.org/koji/taskinfo?taskID=51595616

**Comment by serge-sans-paille** [comment]
All green :-)

**Pull request merged**
