### PR TITLE
Release/0.15.0

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Not in a hurry to do this release, but as usual, feedback from @hroncok , @jeanlaroche , @stefanv, @rgommers, @h-vetinari and @drew-parsons are more than welcome. A lot of compatibility patches in this release, so I will definitively appreciate the extra testing.

**Comment by rgommers** [comment]
This looks fine for SciPy as far as I can tell from a bit of ad-hoc testing. Happy new year!

**Comment by h-vetinari** [comment]
One failure (windows + python 3.12) when [testing](https://github.com/conda-forge/pythran-feedstock/pull/82) builds from this PR in conda-forge:
```
+ pythran -v dprod.py
INFO:      sys file exists: D:\bld\pythran_1704164495051\_test_env\Lib\site-packages\pythran\pythran.cfg
INFO: platform file exists: D:\bld\pythran_1704164495051\_test_env\Lib\site-packages\pythran\pythran-win32.cfg
WARNING:     user file does not exist: C:\Users\VssAdministrator\.pythranrc
INFO: pythranrc section [pythran] is valid and options are correct
INFO: pythranrc section [typing] is valid and options are correct
INFO: pythranrc section [backend] is valid and options are correct
INFO: pythranrc section [compiler] is valid and options are correct
WARNING: Failed to find 'pythran-openblas' package. Please install it or change the compiler.blas setting. Defaulting to 'blas'
running build_ext
building 'dprod' extension
creating C:\Users\VSSADM~1\AppData\Local\Temp\tmpyv8us63d\Release
creating C:\Users\VSSADM~1\AppData\Local\Temp\tmpyv8us63d\Release\Users
creating C:\Users\VSSADM~1\AppData\Local\Temp\tmpyv8us63d\Release\Users\VSSADM~1
creating C:\Users\VSSADM~1\AppData\Local\Temp\tmpyv8us63d\Release\Users\VSSADM~1\AppData
creating C:\Users\VSSADM~1\AppData\Local\Temp\tmpyv8us63d\Release\Users\VSSADM~1\AppData\Local
creating C:\Users\VSSADM~1\AppData\Local\Temp\tmpyv8us63d\Release\Users\VSSADM~1\AppData\Local\Temp
%PREFIX%\Library\bin\clang-cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -ID:/bld/pythran_1704164495051/_test_env/Library/include -I%PREFIX%\Lib\site-packages/pythran -I%PREFIX%\Lib\site-packages\numpy\core\include -I%PREFIX%\include -I%PREFIX%\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /TpC:\Users\VSSADM~1\AppData\Local\Temp\tmppt1jzpga.cpp /FoC:\Users\VSSADM~1\AppData\Local\Temp\tmpyv8us63d\Release\Users\VSSADM~1\AppData\Local\Temp\tmppt1jzpga.obj /std:c++14 /w
Executing "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:%PREFIX%\libs /LIBPATH:%PREFIX% /LIBPATH:%PREFIX%\PCbuild\amd64 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\ATLMFC\lib\x64 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64 blas.lib /EXPORT:PyInit_dprod C:\Users\VSSADM~1\AppData\Local\Temp\tmpyv8us63d\Release\Users\VSSADM~1\AppData\Local\Temp\tmppt1jzpga.obj /OUT:C:\Users\VSSADM~1\AppData\Local\Temp\tmpgpl_zjzy\dprod.cp312-win_amd64.pyd /IMPLIB:C:\Users\VSSADM~1\AppData\Local\Temp\tmpyv8us63d\Release\Users\VSSADM~1\AppData\Local\Temp\dprod.cp312-win_amd64.lib
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:%PREFIX%\libs /LIBPATH:%PREFIX% /LIBPATH:%PREFIX%\PCbuild\amd64 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" blas.lib /EXPORT:PyInit_dprod C:\Users\VSSADM~1\AppData\Local\Temp\tmpyv8us63d\Release\Users\VSSADM~1\AppData\Local\Temp\tmppt1jzpga.obj /OUT:C:\Users\VSSADM~1\AppData\Local\Temp\tmpgpl_zjzy\dprod.cp312-win_amd64.pyd /IMPLIB:C:\Users\VSSADM~1\AppData\Local\Temp\tmpyv8us63d\Release\Users\VSSADM~1\AppData\Local\Temp\dprod.cp312-win_amd64.lib
LINK : fatal error LNK1181: cannot open input file 'blas.lib'
```

The [file](https://github.com/conda-forge/pythran-feedstock/blob/main/recipe/dprod.py) in question is pretty basic. It's possible that this just needs some new configuration for python 3.12 (c.f. warning about missing `pythran-openblas`, which I'm not familiar with).

**Comment by serge-sans-paille** [comment]
@h-vetinari : indeed the blas automatic configuration seems to be a bit weak on windows... one option to fix that should be to install the `pythran-openblas` package, but that's far from ideal (but it's tested through github actions). I've pushed an update that changes the fallback and should work in your case

**Comment by h-vetinari** [comment]
Thanks a lot for the update, with the current state of this PR everything passes in https://github.com/conda-forge/pythran-feedstock/pull/82 👍

**Comment by serge-sans-paille** [comment]
Great, I'll be doing a release at the end of the week if I don't get any negative feedback then.

**Comment by h-vetinari** [comment]
Would be amazing if 0.15 could include #2168, because then we could _finally_ [fix](https://github.com/scipy/scipy/pull/19810) `NPY_NO_DEPRECATED_API` in scipy without having to depend on unreleased pythran commits.

**Comment by serge-sans-paille** [comment]
Release done https://pypi.org/project/pythran/0.15.0/ tag set https://github.com/serge-sans-paille/pythran/releases/tag/0.15.0

Thank you all for the release testing o/

**Comment by drew-parsons** [comment]
Builds fine in debian, with python 3.12, boost 1.83 and xsimd 10.0.0.

**Pull request merged**
