### PR TITLE
Feature/denone

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@diorcety can you check this solves your issues with None?

**Comment by serge-sans-paille** [comment]
@diorcety thanks for the live feedback. This should be okay now?

**Comment by diorcety** [comment]
Yes, it's 👍

**Comment by serge-sans-paille** [comment]
This is definitievely not the way too go, fat too hacky, I'll put this one in pause and rework it later.

**Comment by serge-sans-paille** [comment]
Obsoleted by #939

**Pull request closed without merging**
