### PR TITLE
Feature/xsimd

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by wolfv** [comment]
hmm there seems to be a problem with the int16 `min` thing! good that these tests found it + sorry :)

**Comment by serge-sans-paille** [comment]
ok, there seems to be an issue with copysign under windows :-) cc @wolfv

**Comment by serge-sans-paille** [comment]
yeah I did

**Comment by wolfv** [comment]
There seems to be a problem with `_mm256_xor_si256` which doesn't exist for `AVX`, only for `AVX2`. I'll take care of that.

**Comment by serge-sans-paille** [comment]
@wolfv I'll merge that one if it validates. Thanks a lot for the xsimd support!

**Comment by wolfv** [comment]
awesome, really happy to see this land in pythran!

**Pull request merged**
