### PR TITLE
Only link with blas when needed

### LINKED ISSUE #2203: error "cannot find -lopenblas: No such file or directory" on python 3.12
Hello,

I get this error: "/home/runner/micromamba/envs/test-env/compiler_compat/ld: cannot find -lopenblas: No such file or directory" when trying to build pylandstats. It seems that this only happens in Python 3.12 - see the logs [here](
https://github.com/martibosch/pylandstats/actions/runs/8899499863/job/24439006700). Any clues on how to solve this?

Thank you. Best,
Martí

### PR DESCRIPTION
**Pull request by serge-sans-paille**
Based on the included headers, pythran now automatically removes the blas dependency.

Also do some cleanups (removing debug lines, some formatting, fix imatmul headers).

Fix #2203

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@martibosch : this one is finally green. It should remove the dep on openblas on your project :-)

**Comment by martibosch** [comment]
unluckily I got the same error both locally and [in github actions](https://github.com/martibosch/pylandstats/actions/runs/9074225275/job/24932619426) :(

**Comment by martibosch** [comment]
sorry, I made a mistake in the requirement syntax. After fixing, everything is working: https://github.com/martibosch/pylandstats/actions/runs/9077046472

should I release now with the git-branch requirement in pyproject.toml, or should i wait (e.g., maybe you remove feature branches or you plan a tagged release very soon).

Thank you again!

**Comment by serge-sans-paille** [comment]
On Tue, May 14, 2024 at 03:02:43AM -0700, Martí Bosch wrote:
> sorry, I made a mistake in the requirement syntax. After fixing, everything is
> working: [1]https://github.com/martibosch/pylandstats/actions/runs/9077046472
> 
> should I release now with the git-branch requirement in pyproject.toml, or
> should i wait (e.g., maybe you remove feature branches or you plan a tagged
> release very soon).

Great! Release incoming this week or the week after :-)

**Pull request merged**
