### PR TITLE
Handle fast indexing of gexpr through tuple of indices

### LINKED ISSUE #796: Huge memory consumption and/or crash (pythran 0.8.4.post0)
I am not able anymore to compile this code with Pythran 0.8.4.post0. It compiles fine with Pythran 0.8.3.

```
import numpy as np

# pythran export compute_subpix_2d_gaussian2(float32[][], int, int)
def compute_subpix_2d_gaussian2(correl, ix, iy):
    correl_crop = correl[iy-1:iy+2, ix-1:ix+2]
    # hoops, pythran crashes because of this line
    # correl_crop[correl_crop < 0] = 1e-6

    # we write it like this to please pythran
    tmp = np.where(correl_crop < 0)
    for i0, i1 in zip(tmp[0], tmp[1]):
        correl_crop[i0, i1] = 1e-6

    c10 = 0
    c01 = 0
    c11 = 0
    c20 = 0
    c02 = 0
    for i in range(3):
        for j in range(3):
            c10 += (i-1)*np.log(correl_crop[j, i])
            c01 += (j-1)*np.log(correl_crop[j, i])
            c11 += (i-1)*(j-1)*np.log(correl_crop[j, i])
            c20 += (3*(i-1)**2-2)*np.log(correl_crop[j, i])
            c02 += (3*(j-1)**2-2)*np.log(correl_crop[j, i])
            c00 = (5-3*(i-1)**2-3*(j-1)**2)*np.log(correl_crop[j, i])

    c00, c10, c01, c11, c20, c02 = \
        c00/9, c10/6, c01/6, c11/4, c20/6, c02/6
    deplx = (c11*c01-2*c10*c02)/(4*c20*c02-c11**2)
    deply = (c11*c10-2*c01*c20)/(4*c20*c02-c11**2)
    return deplx, deply, correl_crop

```

With Pythran 0.8.4.post0, g++ consumes too much memory (more than 12 Go) and finally crashes... 

Same behavior with GCC 4.9 and 5.4...

### PR DESCRIPTION
**Pull request by serge-sans-paille**
Fix #796

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@paugier can you confirm this solves your issue?

**Comment by paugier** [comment]
Unfortunately I still have the problem. Huge memory consumption to compile the file.

Note that I get these warnings:
```
/home/pierre/opt/miniconda3/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/interval.py:77: RuntimeWarning: invalid value encountered in multiply
  res = [v1 * v2 for v1, v2 in
/home/pierre/opt/miniconda3/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/interval.py:64: RuntimeWarning: invalid value encountered in double_scalars
  return Interval(self.low - other.high, self.high - other.low)
```

**Comment by serge-sans-paille** [comment]
I have the huge memory consumption too, but it is within reasonable
bounds (i.e. it does not crash) now. Not on your side?

**Comment by serge-sans-paille** [comment]
Still merging because it fixes an API issue, but I keep in mind your compile time problem.

**Comment by serge-sans-paille** [comment]
@paugier note that with clang, this compiles super-fast. So it's likely to be a gcc performance issue :-/

**Pull request merged**
