### PR TITLE
Improve type conversions from str

### LINKED ISSUE #985: Float conversion issue
This following example fails with pythran

hh.py:
```
import numpy

#pythran export aa(str):
def aa(x):
    return float(x)
```

ii.py:
```
import numpy
import hh

x = hh.aa("0.000172")
print(x)
assert x == 0.000172
```

### PR DESCRIPTION
**Pull request by diorcety**
Fix #985

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@diorcety validation fails, I let you insypect that

**Comment by diorcety** [comment]
I doesn't understand the test, because if you add this test. This test fails on master, not with my PR
```
    def test_generator_handler_name2(self):
        code = '''
            def foo(x):
                if x > 2:
                    for i in range(x):
                        if i > 1:
                            break
                        yield i
                else:
                    for i in ["1"] * x:
                        if len(i) > 1:
                            break
                        yield i

            def test_generator_handler_name2(n):
                return list(foo(n))'''
        self.run_test(code,
                      2,
                      test_generator_handler_name2=[int])
```

**Comment by serge-sans-paille** [comment]
@diorcety I'm ok with that PR, just missing the test update we discussed about.

**Comment by diorcety** [comment]
https://github.com/serge-sans-paille/pythran/pull/986/commits/7d65789312a9cb5abb0c5514cb675d077e4f876d#diff-d3c9d2d871f95edff366faf729fb7f3eR255

**Pull request merged**
