### PR TITLE
Fix OMP on Windows

### PR DESCRIPTION
**Pull request by diorcety**
Without this modification, the following issue apprears

`pythran\pythonic/utils/broadcast_copy.hpp(71): error C3016: 'i': index variable in OpenMP 'for' statement must have signed integral type`

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
This breaks the validation :-)

**Comment by diorcety** [comment]
GCC issue?

**Comment by serge-sans-paille** [comment]
I can reproduce with gcc higher version, let me check that first.

**Comment by serge-sans-paille** [comment]
I can reproduce with gcc higher version, let me check that first.oh, and I cna even reproduce on master without your patch :-/

**Comment by serge-sans-paille** [comment]
Yipee!

**Pull request merged**
