### PR TITLE
0.12.0 - arar

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
I'll probably add #2018 for the scipy people, but @jeanlaroche, @drew-parsons, @hroncok and @rgommers this is going to be the next release of pythran, you can use that branch to test the compatibility with your distrib / project :-)

**Comment by rgommers** [comment]
Thanks @serge-sans-paille! I just happened to have a need for this - I installed the Intel compilers on Linux, and the build failed with Pythran 0.11 and it worked fine with this branch.

**Comment by serge-sans-paille** [comment]
Thanks @rgommers !

**Comment by serge-sans-paille** [comment]
@all : if I get no error report, I'll do a release around Wednesday the 28th of September, 2022

**Comment by hroncok** [comment]
Taking a look now. Was busy, sorry.

**Comment by hroncok** [comment]
Fedora 38 scratch build: https://koji.fedoraproject.org/koji/taskinfo?taskID=92355158

**Comment by hroncok** [comment]
And Fedora dependent packages https://copr.fedorainfracloud.org/coprs/churchyard/pythran-0.12.0/builds/

**Comment by hroncok** [comment]
Fedora looks all good.

**Comment by serge-sans-paille** [comment]
aas green as a clover, thanks @hroncok !

**Pull request merged**
