### PR TITLE
More portable gmp detection

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by nbecker** [comment]
I'm a git newb (long time hg user), so maybe I didn't do this correctly?

python2 setup.py build
/usr/lib/python2.7/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.7.5post2' to '0.7.5.post2'
  normalized_version,
running build
running build_py
package init file 'pythran/pythonic/__init__.py' not found (or not a regular file)
Copying nt2 and its dependencies
Trying to compile GMP dependencies.
cc -c /tmp/tmpRDi32_.c -o tmp/tmpRDi32_.o
cc tmp/tmpRDi32_.o -lgmp -o a.out
[nbecker@nbecker7 pythran]$ git branch
* (HEAD detached at origin/fix/gmp-detection)
  master

**Comment by serge-sans-paille** [comment]
On Thu, Jun 23, 2016 at 06:19:03AM -0700, ndbecker wrote:
> I'm a git newb (long time hg user), so maybe I didn't do this correctly?
> 
> python2 setup.py build
> /usr/lib/python2.7/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.7.5post2' to '0.7.5.post2'
>   normalized_version,
> running build
> running build_py
> package init file 'pythran/pythonic/__init__.py' not found (or not a regular file)
> Copying nt2 and its dependencies
> Trying to compile GMP dependencies.
> cc -c /tmp/tmpRDi32_.c -o tmp/tmpRDi32_.o
> cc tmp/tmpRDi32_.o -lgmp -o a.out
> [nbecker@nbecker7 pythran]$ git branch
> * (HEAD detached at origin/fix/gmp-detection)
>   master

looks good to me :-) thanks!

**Comment by nbecker** [comment]
problem is it needs to either build with g++ or add -lstdc++, it's trying to build with cc, which won't work for c++

**Comment by serge-sans-paille** [comment]
yes, that's why I chaned the test case to be a plain C test case so that we don'"t run into your issue

**Pull request merged**
