### PR TITLE
Rework and improve expression broadcasting support

### LINKED ISSUE #1163: Compilation issue depending on instruction decomposition
Maybe there is two issue with this test:
- Following the decomposition the generated code is not the same (after optimizations, it should be?)
- That the code doesn't work in one case

```
import numpy as np
import numpy.linalg as npl

def _get_cross(a, b):
    #return np.cross(far - center, coords - center)
    #return a[..., 0] * b[..., 1] - a[..., 1] * b[..., 0]
    return a[0] * b[:, :, 1] - a[1] * b[:, :, 0]


def _get_mgrid(shape):
    #return np.mgrid[:shape[0], :shape[1]]
    xx = np.empty(shape, dtype=int)
    xx.T[:] = np.arange(0, shape[0], 1, dtype=int)
    yy = np.empty(shape, dtype=int)
    yy[:] = np.arange(0, shape[1], 1, dtype=int)
    return xx, yy

#pythran export bb((int, int), (float, float), float)
def bb(shape, center, angle):
    xx, yy = _get_mgrid(shape)
    coords = np.rollaxis(np.array([xx, yy]), 0, 3)
    far = center + np.array([np.cos(angle), np.sin(angle)]) * 100

    # Don't work
    #z = np.absolute(_get_cross(far - center, coords - center))
    #return z

    # Work
    y = _get_cross(far - center, coords - center)
    return np.absolute(y)

```

### PR DESCRIPTION
**Pull request by serge-sans-paille**
It's now possible to slice, index, etc expression involving broadcasting.

Fix #1163

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@diorcety can you confirm this one is okay for you?

**Comment by diorcety** [comment]
@serge-sans-paille Almost.
Is it normal that doesn't work if you force center to be an array?
`center = np.asarray(center)`

**Comment by serge-sans-paille** [comment]
@diorcety should be fixed by now!

**Comment by diorcety** [comment]
👍

**Comment by serge-sans-paille** [comment]
Hell yeah!

**Pull request merged**
