### PR TITLE
encoded content of cell (type: str) to avoid hashlib error

### PR DESCRIPTION
**Pull request by flothesof**
Hi @serge-sans-paille 

As described during the pythran tutorial, pull request to fix the cell (type: str) encoding bug.

Best,
Florian

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
It's a good place to add a test case about this. Can you do that or do you prefer I take care of it?

**Comment by flothesof** [comment]
Hi Serge,
Unfortunately I don't know how to do that. Would you be so kind and add it
yourself?
Thanks.
Best regards
Florian

**Comment by serge-sans-paille** [comment]
ok, let's wait until 90804e04c349d8c6ac94c0a094c6daa28b7cb95f gets merged, then you can update the .travis.yml file to also test ipython on Python3. keep in touch!

**Comment by flothesof** [comment]
Ok, I'll wait until its merged and will try to insert a unit test following the one you already have under Python 2, but for Python 3, as mentioned in your .travis.yml: 
`- PYTHON_VERSION=2 TESTCASE=pythran/tests/test_ipython.py`
Thanks.

**Comment by serge-sans-paille** [comment]
On Fri, Jul 07, 2017 at 12:39:05PM +0000, Florian LB wrote:
> Ok, I'll wait until its merged and will try to insert a unit test following the one you already have under Python 2, but for Python 3, as mentioned in your .travis.yml: 
> `- PYTHON_VERSION=2 TESTCASE=pythran/tests/test_ipython.py`

Yeah, that's actually just a matter of removing PYTHON_VERSION=2 from
this line :-)

**Comment by serge-sans-paille** [comment]
@flothesof you can rebase on master and update the trabvis file!

**Comment by flothesof** [comment]
I just rebased and added the test for travis under Python 3. Let's see how it goes.

**Comment by flothesof** [comment]
Actually, I tried to run local tests with `python setup.py test` but ran into an error. The trace is:
```
============================================================ test session starts ============================================================
platform darwin -- Python 3.6.1, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /Users/kappamaki/workspace/pythran, inifile: setup.cfg
plugins: pep8-1.0.6
collected 2498 items / 1 errors 

================================================================== ERRORS ===================================================================
_____________________________________________ ERROR collecting pythran/tests/test_exception.py ______________________________________________
pythran/tests/test_exception.py:299: in <module>
    args = exception_args[exception]
E   KeyError: 'BlockingIOError'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================== 1 error in 7.12 seconds ==========================================================

```
What should I do?

**Comment by serge-sans-paille** [comment]
``python setup.py test`` only works for python2 :-) only a subset of tests are compatible with python2, it's hard coded in the travis files... Travis looks happy with your change, so am I

**Pull request merged**
