### PR TITLE
Accept transposed parameters

### PR DESCRIPTION
**Pull request by serge-sans-paille**
It relies on a new type annotation in the Pythran export (namely the T
qualifier) so that 2D array arguments with Fortran layout are accepted as
transposed 2D arrays with C layout.

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
This pass is now ok for review! It's very smart, try it :-)

**Comment by pbrunet** [comment]
I think you didn't push in the correct branch for nary.

**Comment by serge-sans-paille** [comment]
That's on purpose, because the commits are somehow related

**Comment by serge-sans-paille** [comment]
@pbrunet this (huge) PR has been updated, taking into account all your comments!

**Comment by serge-sans-paille** [comment]
Updated, thanks @pbrunet !

**Comment by pbrunet** [comment]
Sorry for this long review. I didn't really look at nexpr before yesterday and a discussion may be faster than PR review of the code.
Do you know why github don't want to auto merge this PR?

**Comment by serge-sans-paille** [comment]
No problem. I had a hard time writing this PR, so there are a lot of
flaws. I'll check the merge (didn't try to rebase)

**Comment by serge-sans-paille** [comment]
updated for clang++ and g++ compatibility

**Comment by serge-sans-paille** [comment]
updated again

**Comment by serge-sans-paille** [comment]
@pbrunet : breaking news: travis says yes to this PR ;-)

**Comment by serge-sans-paille** [comment]
except it's not mergeable :-/

**Comment by pbrunet** [comment]
I am almost done with it :-) I am currently reviewing 3153e53 :-). We will see for rebase soon.

**Comment by pbrunet** [comment]
:-) I just need your help on some points but it looks fine.
I can point commented code in your commits if you want and then merge it.

**Comment by serge-sans-paille** [comment]
@pbrunet travis is ok, except for the pep8 due to a pep8 update fixed by #390

**Comment by serge-sans-paille** [comment]
ok for Vincent's advice. Did I miss something else in this PR?

**Comment by pbrunet** [comment]
These comment may be issues : 
- https://github.com/serge-sans-paille/pythran/commit/b309f9316eda9dbc7a505bb0486932330cd958c2#commitcomment-9659585
- https://github.com/serge-sans-paille/pythran/commit/1177634ee2d5ea7e8844d313eab44f497f2b8004#commitcomment-9658726

Can you give me some explication so that I understand what is happening?

**Pull request merged**
