### PR TITLE
0.13.0 - bouc'hal

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
cc @rgommers @jeanlaroche @paugier  @hroncok  @stefanv and @drew-parsons,  can you beta test this release and report here? Thanks!

**Comment by drew-parsons** [comment]
Builds fine for debian, tests are passing.

https://buildd.debian.org/status/package.php?p=pythran&suite=experimental

**Comment by andyfaff** [comment]
I (scipy maintainer) just tried to build `scipy/main` using `pip install git+https://github.com/serge-sans-paille/pythran.git@feature/0.13.0` to install pythran.
The build completes and the test suite goes to completion.

**Comment by mattip** [comment]
Closes #2101

**Comment by jeanlaroche** [comment]
Tried this branch on my code, everything seems to work normally.
Awesome!

Jean

**Comment by stefanv** [comment]
All looking good for skimage as well.

**Comment by serge-sans-paille** [comment]
Thank you all for the testing! As this release contains a compatibility patch for the latest gast release, I'll publish that today.

**Comment by h-vetinari** [comment]
Now that 0.13 has made it to scipy's CI, the gast problems are gone, but I'm seeing another failure that's not there with pythran 0.12.1 & gast 0.5.3, at least on windows & musl
```
[827/1624] Compiling C++ object scipy/stats/_stats_pythran.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__stats_pythran.cpp.o
FAILED: scipy/stats/_stats_pythran.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__stats_pythran.cpp.o 
c++ -Iscipy/stats/_stats_pythran.cpython-310-x86_64-linux-gnu.so.p -Iscipy/stats -I../scipy/stats -I../../../usr/lib/python3.10/site-packages/pythran -I../../../usr/lib/python3.10/site-packages/numpy/core/include -I/usr/include/python3.10 -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++14 -O2 -g -fPIC -DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DPYTHRAN_BLAS_NONE -Wno-cpp -Wno-deprecated-declarations -Wno-unused-but-set-variable -Wno-unused-function -Wno-unused-variable -Wno-int-in-bool-context -MD -MQ scipy/stats/_stats_pythran.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__stats_pythran.cpp.o -MF scipy/stats/_stats_pythran.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__stats_pythran.cpp.o.d -o scipy/stats/_stats_pythran.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__stats_pythran.cpp.o -c scipy/stats/_stats_pythran.cpp
In file included from ../../../usr/lib/python3.10/site-packages/pythran/xsimd/xsimd.hpp:55,
                 from ../../../usr/lib/python3.10/site-packages/pythran/pythonic/include/numpy/ceil.hpp:8,
                 from scipy/stats/_stats_pythran.cpp:34:
../../../usr/lib/python3.10/site-packages/pythran/xsimd/arch/xsimd_scalar.hpp:465:25: error: exponent has no digits
  465 |         return std::exp(0x1.26bb1cp+1f * x);
      |                         ^~~~~~~~~~~
../../../usr/lib/python3.10/site-packages/pythran/xsimd/arch/xsimd_scalar.hpp:469:25: error: exponent has no digits
  469 |         return std::exp(0x1.26bb1bbb55516p+1 * x);
      |                         ^~~~~~~~~~~~~~~~~~
../../../usr/lib/python3.10/site-packages/pythran/xsimd/arch/xsimd_scalar.hpp: In function 'float xsimd::exp10(const float&)':
../../../usr/lib/python3.10/site-packages/pythran/xsimd/arch/xsimd_scalar.hpp:465:37: error: unable to find numeric literal operator 'operator""f'
  465 |         return std::exp(0x1.26bb1cp+1f * x);
      |                                     ^~
../../../usr/lib/python3.10/site-packages/pythran/xsimd/arch/xsimd_scalar.hpp:465:37: note: use '-fext-numeric-literals' to enable more built-in suffixes
```

Since this is failing in the xsimd-headers, this doesn't look like a scipy-problem.

**Comment by serge-sans-paille** [comment]
I think upgrading to xsimd 11 fixes the issue, can you confirm on https://github.com/serge-sans-paille/pythran/pull/2103 ?

**Comment by h-vetinari** [comment]
> I think upgrading to xsimd 11 fixes the issue, can you confirm on #2103 ?

Thanks for the quick response. I gave it a shot in https://github.com/scipy/scipy/pull/15841/commits/3ef97d93c97f4fbb3fa2dc6736a436dc26b37d5f, and unfortunately, it didn't help, see e.g. [this](https://cirrus-ci.com/task/5735095047290880) CI run:
```
python -m pip install git+https://github.com/serge-sans-paille/pythran.git@feature/xsimd-11
Collecting git+https://github.com/serge-sans-paille/pythran.git@feature/xsimd-11
  Cloning https://github.com/serge-sans-paille/pythran.git (to revision feature/xsimd-11) to /tmp/pip-req-build-tskks_3k
  Running command git clone --filter=blob:none --quiet https://github.com/serge-sans-paille/pythran.git /tmp/pip-req-build-tskks_3k
  Running command git checkout -b feature/xsimd-11 --track origin/feature/xsimd-11
  branch 'feature/xsimd-11' set up to track 'origin/feature/xsimd-11'.
  Switched to a new branch 'feature/xsimd-11'
  Resolved https://github.com/serge-sans-paille/pythran.git to commit 0ce82efbdecb8847698ec4206d42b8a624e7d936
  [...]
Successfully installed beniget-0.4.1 gast-0.5.4 ply-3.11 pythran-0.13.0
```
which ends in the same error.

Taking a step back: as I [noted](https://github.com/serge-sans-paille/gast/issues/74) on the gast issue, I don't think it's sustainable to keep layering changes on top of requiring bleeding-edge-but-still-being-released-(or-debugged) releases. This should be fixed for pythran 0.12 first, then we can take more time for testing 0.13 properly, rather than frantically trying to unblock various broken CI pipelines.

**Comment by serge-sans-paille** [comment]
@h-vetinari my bad, the patch in xsimd is not part of 11.0.0, it's actually https://github.com/xtensor-stack/xsimd/commit/a1e07510dd81a0b074d2cef8e09bf8e59b926aae we need. If you confirm, I can backport this to pythran 13.0.0

**Comment by h-vetinari** [comment]
Based on the errors & the commit you linked, that looks very realistic. Though to test it, I'd need you to pick that patch into https://github.com/serge-sans-paille/pythran/pull/2103 (or some other branch I can point to).

**Comment by h-vetinari** [comment]
Assuming that's the issue, a potential work-around (for anyone still affected after the gast stuff) would be to use C++17.

**Comment by serge-sans-paille** [comment]
@h-vetinari https://github.com/serge-sans-paille/pythran/pull/2104 ?

**Comment by serge-sans-paille** [comment]
FYI I've just released 0.13.1 (see https://github.com/serge-sans-paille/pythran/pull/2105) that backports a compatibility patch for xsimd.

**Pull request merged**
