### PR TITLE
Fix arguments to rfft and irfft

### PR DESCRIPTION
**Pull request by jeanlaroche**

### CODE REVIEW

**Comment by cycomanic** [comment]
This fails if you only specify the `axis` kwarg (I've encountered this as well).

**Comment by jeanlaroche** [comment]
> 
> 
> This fails if you only specify the `axis` kwarg (I've encountered this as well).

Ah ok, I'll fix and add a test.

**Comment by jeanlaroche** [comment]
I fixed the issue that arose when one of the arguments was missing.

**Comment by serge-sans-paille** [comment]
Thanks!

**Pull request merged**
