### PR TITLE
Feature/numpy random normal

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@pbrunet : I took into account your review, thxs a lot! It's much better now.

**Comment by serge-sans-paille** [comment]
@pbrunet I'm green tadoudidadouda

**Comment by pbrunet** [comment]
This is great!! I asked for this but some tests modification are missing. Unchanged tests are : argmin, argmax, cumproduct, ravel, take

**Comment by serge-sans-paille** [comment]
`cumprod` is a method, but curiously enough, `cumproduct` is a function :-)

**Comment by serge-sans-paille** [comment]
And `take` is marked as skip :-) I fixed the other tests.

**Comment by serge-sans-paille** [comment]
@pbrunet should be ok now, thxs!

**Pull request merged**
