### PR TITLE
Correct support of develop target for setup.py

### LINKED ISSUE #783: `python setup.py develop` to work on pythran code?
Hi,

I'd like to work on pythran code and I try to use `python setup.py develop`. It would be nice to be able to use this instead of `python setup.py install`.

It does not work because g++ does not find header files.

I remember that I read something about this issue in the documentation but I can not find it anymore. Did I dream?

What is the recommend method to install pythran when one wants to modify its code?

### PR DESCRIPTION
**Pull request by serge-sans-paille**
Fix #783 and improves #786.

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@paugier and @flothesof can you confirm this fixes the ``python setup.py develop`` target? Thanks!

**Comment by paugier** [comment]
I confirm that `python setup.py develop` works well for me. Very convenient!

**Comment by flothesof** [comment]
I just tested this from a clean conda environment where I checked out this branch. It worked fine on the dprod example from the Readme. So I can confirm it works on Mac. 

Thanks!

**Comment by serge-sans-paille** [comment]
Thanks @flothesof and @paugier for the feedback!

**Pull request merged**
