### PR TITLE
Remove xrange in python3

### PR DESCRIPTION
**Pull request by diorcety**
- Remove xrange support in Python 3 (not existing)
- Fix loop optimizatin with xrange/range support on python 2 and range on python 3
- Support of past module xrange/range. Allow to have a python 2 & 3 compatible code

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Not sure I'm interested in supporting the ``past`` module. Pythran is going to slowly drop support for python2 anyway...

**Comment by diorcety** [comment]
Okay the Travis failures don't seem related to my PR

**Comment by serge-sans-paille** [comment]
This also require fixing some test case, i'll handle that.

**Comment by serge-sans-paille** [comment]
Obsoleted by #980

**Pull request closed without merging**
