### PR TITLE
Release the GIL when we don't need it anymore

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@pbrunet Travis is almost finished, this one should be ok.

**Comment by serge-sans-paille** [comment]
travis is ok :-)

**Comment by pbrunet** [comment]
Looks nice. I just wonder if we should run test twices: once with one threads, once with 2 or 4 and check we are faster?

**Comment by serge-sans-paille** [comment]
On Tue, Dec 20, 2016 at 12:15:42AM -0800, pbrunet wrote:
> Looks nice. I just wonder if we should run test twices: once with one threads, once with 2 or 4 and check we are faster?

We could do this with a call to sleep because it does no consume CPU. We
can't do this otherwise because we have no control over the number of
available threads. I'll add this test case.

**Comment by serge-sans-paille** [comment]
@pbrunet turns out setting up the test will be quite complicated. I did it manually and it's ok, don't wanant to bother more, you can merge if that's ok with you too.

**Pull request merged**
