### PR TITLE
Centralize all pythran-managed allocation in one place

### PR DESCRIPTION
**Pull request by serge-sans-paille**
This should make it easier to instrument allocations.

As a side effect slightly improve some string manipulation.

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
cc @jeanlaroche

**Comment by serge-sans-paille** [comment]
@jeanlaroche : I've added a flag `--trace-allocations` to automate the instrumentation of memory allocation, is that close to what you had in mind?

**Comment by jeanlaroche** [comment]
This works really well and is super super useful for me!

**Comment by serge-sans-paille** [comment]
I've added some extra documentation, will merge afterward

**Pull request merged**
