### PR TITLE
Portable blas configuration

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@bermanmaxim does this PR solve your issue?

**Comment by bermanmaxim** [comment]
Hello, I will check it out on saturday and report the results, thank you!

**Comment by bermanmaxim** [comment]
Hi Serge, it does work works with this pull request -- after inserting blas=mkl in my configuration. Thanks! Maxim.

**Comment by serge-sans-paille** [comment]
Great \o/
Thanks for testing!

**Pull request merged**
