### PR TITLE
Implement numpy.flip

### PR DESCRIPTION
**Pull request by diorcety**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@diorcety there's only one validation issue: you should apply clang-format-3.6 to you cpp files.

**Comment by serge-sans-paille** [comment]
Thxs! Did you test the perf compared to numpy.flip?

**Comment by serge-sans-paille** [comment]
ok, it turns out flip is implemented as an array view so O(1) in numpy. We are much slower....

**Comment by diorcety** [comment]
Oh, I didn't think to that. I started from the roll source, i didn't know that was done by view and how to do this in pythran

**Pull request merged**
