### PR TITLE
Fix compilation of fake_shape under g++4.8

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Travis is OK with this one. It will probably become useless soon, but it fixes Valerio's issue, so it's worth being merged.

**Comment by serge-sans-paille** [comment]
obsoleted by #436

**Comment by pbrunet** [comment]
... I was waiting for travis. Finally, should I merge it or not? (If it have to be merge, you can do it)

**Comment by decabyte** [comment]
@serge-sans-paille, @pbrunet yes I can confirm that this is fixing the issue.

**Comment by serge-sans-paille** [comment]
@decabyte : does #436 fixes it too?

**Comment by decabyte** [comment]
@serge-sans-paille yes, #436 compiles correctly the snippet I posted. :+1:

**Comment by pbrunet** [comment]
The other one is accepted.

**Pull request closed without merging**
