### PR TITLE
Fix ndarray pretty printer

### LINKED ISSUE #1229: use of unitialized value

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by nbecker** [comment]
No, that fixes the print, but not the original problem.  Without any print statement, I'm getting
```
==19729== Conditional jump or move depends on uninitialised value(s)
==19729==    at 0x18C90196: __lower_bound<double const*, double, __gnu_cxx::__ops::_Iter_less_val> (stl_algobase.h:959)
==19729==    by 0x18C90196: lower_bound<double const*, double> (stl_algobase.h:993)
==19729==    by 0x18C90196: searchsorted<double, (anonymous namespace)::pythonic::types::ndarray<double, (anonymous namespace)::pythonic::types::pshape<long int> > > (searchsorted.hpp:27)
==19729==    by 0x18C90196: operator()<(anonymous namespace)::pythonic::types::ndarray<double, (anonymous namespace)::pythonic::types::pshape<long int> >, double&> (searchsorted.hpp:27)
==19729==    by 0x18C90196: __pythran__empirical_prob::empirical::type<(anonymous namespace)::pythonic::types::ndarray<double, (anonymous namespace)::pythonic::types::pshape<long> >&, double&>::result_type __pythran__empirical_prob::empirical::operator()<(anonymous namespace)::pythonic::types::ndarray<double, (anonymous namespace)::pythonic::types::pshape<long> >&, double&>((anonymous namespace)::pythonic::types::ndarray<double, (anonymous namespace)::pythonic::types::pshape<long> >&, double&) const [clone .isra.248] (tmpghl7d4_c.cpp:68)
==19729==    by 0x18C91C77: empirical0 (tmpghl7d4_c.cpp:78)
==19729==    by 0x18C91C77: __pythran_wrap_empirical0 (tmpghl7d4_c.cpp:98)
==19729==    by 0x18C91C77: operator() (tmpghl7d4_c.cpp:110)
==19729==    by 0x18C91C77: handle_python_exception<__pythran_wrapall_empirical(PyObject*, PyObject*, PyObject*)::<lambda()> > (exception_handler.hpp:17)
==19729==    by 0x18C91C77: __pythran_wrapall_empirical(_object*, _object*, _object*) (tmpghl7d4_c.cpp:107)
```
...
```
Traceback (most recent call last):
  File "./grow.py", line 410, in <module>
    run()
  File "./grow.py", line 335, in run
    original_pts, best_circles, best_Us, best_Vs, best_Ws, best_clean_cnt = test2(circle_maker=circle_maker, alpha=opt.alpha, plot=opt.plot, trials=opt.trials, epochs=opt.epochs, npoints=opt.npoints, size=opt.size, randomize='mincircle' in opt.randomize, remove_redundant=opt.remove_redundant, do_cleanup=opt.cleanup, short=opt.short,animate=opt.animate)
  File "./grow.py", line 167, in test2
    U, V, W, center, radius = grow (P, pts, 1, circle_maker, alpha=alpha, randomize=randomize, short=short, do_animate=animate)
  File "./grow.py", line 68, in grow
    V = np.append (V, U[selected])
IndexError: index 7 is out of bounds for axis 0 with size 7
```
The program crashes with indexerror, which is impossible.  I' believe that this uninitialized value is causing the problem.  Putting in a print statement make the problem disappear (and the program doesn't crash).

**Comment by serge-sans-paille** [comment]
Can you provide a minimal reproducer (I need a simple call site)

**Comment by nbecker** [comment]
I think I know what was happening here. 
We have fractions = d_i / \sum(d_i),
thresholds = cumsum(fractions).
This means thesholds[-1] == 1.  But due to floating inprecision, thesholds[-1] may not be exactly -1.
This is causing searchsorted to misbehave if the value returned by ranf is close enough to 1.

For now I'm not using pythran's ranf, but passing in my own random value as an argument, which I really wanted anyway, because I need reproducible results.

But there still seems to be a problem with searchsorted reading an undefined memory value.

So far I haven't been able to find a small test case to reproduce.

BTW, same results with clang instead of gcc

**Comment by nbecker** [comment]
Further work on this.  I was wrong.  This code is buggy as hell.  Let's look at the current version:
```
#pythran export empirical(float[:], float, float)
def empirical(ds, alpha, x):
    sds = np.sort(ds)
    ds_to_the_alpha = sds**alpha 
    fractions = ds_to_the_alpha #/ sum (ds_to_the_alpha)
    thresholds = np.cumsum(fractions)
    thresholds /= thresholds[-1]
    i = find_first (thresholds, lambda u: x < u)
    if i is None:
        #print (ds, fractions, thresholds, x)
        print (ds, x)
    #i = np.searchsorted (thresholds, x)
    return i
#pthran export find_first(float[:], bool (float))
def find_first (seq, pred):
    for i,x in enumerate (seq):
        if pred(x):
            return i
    return None
```

In this code, if the print statement is uncommented, then the program completes normally.  If the print statement is commented, the program crashes.  It seems the possibility that the values of 'fractions' and/or 'thresholds' might be used causes a difference in behavior.  Are you familiar with quantum mechanics?

**Pull request merged**
