### PR TITLE
0.14.0 - falzig

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Preparing the release. As usual, @jeanlaroche @stefanv @rgommers @h-vetinari, @hroncok, @paugier and @drew-parsons , your feedbacks are welcome!

**Comment by stefanv** [comment]
All good on scikit-image; thanks for checking!

**Comment by h-vetinari** [comment]
All good from the conda-forge side as well. 👍

**Comment by rgommers** [comment]
All good for SciPy too.

**Comment by hroncok** [comment]
Building pythran-0.14.0-0.fc40.src.rpm for rawhide
Created task: 105609691
Task info: https://koji.fedoraproject.org/koji/taskinfo?taskID=105609691

**Comment by hroncok** [comment]
```
=========================== short test summary info ============================
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_logistic1
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_logistic2
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_normal1
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_normal2
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_exponential1
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_exponential2
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_pareto2
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_rayleigh1
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_rayleigh2
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_gumbel1
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_gumbel2
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_sample1
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_lognormal1
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_lognormal2
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_f2 - I...
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_random_sample1
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_randint4
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_poisson1
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_poisson2
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_ranf1
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_gamma2
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_laplace1
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_laplace2
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_random1
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_power2
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_geometric2
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_weibull2
FAILED pythran/tests/test_numpy_random.py::TestNumpyRandom::test_numpy_chisquare2
==== 28 failed, 3554 passed, 56 skipped, 807 warnings in 1217.41s (0:20:17) ====
```

This  is consistent with what we see in the previous version as well. See https://koschei.fedoraproject.org/package/pythran

**Comment by serge-sans-paille** [comment]
@hroncok could that be linked to the use of python 3.12?

**Comment by hroncok** [comment]
https://koschei.fedoraproject.org/package/pythran suggests something in https://koschei.fedoraproject.org/build/15943520 -- most likely scipy.

**Comment by serge-sans-paille** [comment]
@hroncok I *think* I got it fixed with the extra commit added to this PR. at least that's what https://koji.fedoraproject.org/koji/taskinfo?taskID=105672636 suggests.

@rgommers could you also give it a try, that patch is a slight adjustment over one of your recent commit.

**Comment by rgommers** [comment]
That looks good to me, logic seems correct and it works for SciPy.

**Comment by drew-parsons** [comment]
Build is successful on Debian.

**Comment by hroncok** [comment]
Awesome, trying dependent packages in https://copr.fedorainfracloud.org/coprs/churchyard/pythran-0.14.0/builds/

**Comment by hroncok** [comment]
sagemath failed, but that is consistent with https://koschei.fedoraproject.org/package/sagemath

All is well here, thanks!

**Comment by serge-sans-paille** [comment]
cool! I'll do the release in a day or so then!

**Comment by serge-sans-paille** [comment]
Realease done, package should be available on PyPI. Thanks you all o/

**Pull request merged**
